/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DeviceId = IDL.Text;
export const Timestamp = IDL.Int;
export const SleepRecommendation = IDL.Record({
  'suggestedBedtime' : Timestamp,
  'analysisWindowEnd' : Timestamp,
  'analysisWindowStart' : Timestamp,
  'suggestedWakeup' : Timestamp,
});
export const BlinkRate = IDL.Nat;
export const BlinkRateMeasurement = IDL.Record({
  'userPrincipal' : IDL.Opt(IDL.Principal),
  'deviceId' : DeviceId,
  'timestamp' : Timestamp,
  'blinkRate' : BlinkRate,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const VibrationEventId = IDL.Nat;
export const VibrationEvent = IDL.Record({
  'eventId' : VibrationEventId,
  'userPrincipal' : IDL.Opt(IDL.Principal),
  'deviceId' : DeviceId,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearOldData' : IDL.Func([DeviceId, Timestamp], [], []),
  'generateSleepRecommendation' : IDL.Func(
      [DeviceId, Timestamp, Timestamp],
      [SleepRecommendation],
      [],
    ),
  'getBlinkRates' : IDL.Func(
      [DeviceId],
      [IDL.Vec(BlinkRateMeasurement)],
      ['query'],
    ),
  'getBlinkRatesInTimeRange' : IDL.Func(
      [DeviceId, Timestamp, Timestamp],
      [IDL.Vec(BlinkRateMeasurement)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVibrationEvents' : IDL.Func(
      [DeviceId],
      [IDL.Vec(VibrationEvent)],
      ['query'],
    ),
  'getVibrationEventsInTimeRange' : IDL.Func(
      [DeviceId, Timestamp, Timestamp],
      [IDL.Vec(VibrationEvent)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordBlinkRate' : IDL.Func([DeviceId, BlinkRate], [], []),
  'recordVibrationEvent' : IDL.Func([DeviceId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DeviceId = IDL.Text;
  const Timestamp = IDL.Int;
  const SleepRecommendation = IDL.Record({
    'suggestedBedtime' : Timestamp,
    'analysisWindowEnd' : Timestamp,
    'analysisWindowStart' : Timestamp,
    'suggestedWakeup' : Timestamp,
  });
  const BlinkRate = IDL.Nat;
  const BlinkRateMeasurement = IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Principal),
    'deviceId' : DeviceId,
    'timestamp' : Timestamp,
    'blinkRate' : BlinkRate,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const VibrationEventId = IDL.Nat;
  const VibrationEvent = IDL.Record({
    'eventId' : VibrationEventId,
    'userPrincipal' : IDL.Opt(IDL.Principal),
    'deviceId' : DeviceId,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearOldData' : IDL.Func([DeviceId, Timestamp], [], []),
    'generateSleepRecommendation' : IDL.Func(
        [DeviceId, Timestamp, Timestamp],
        [SleepRecommendation],
        [],
      ),
    'getBlinkRates' : IDL.Func(
        [DeviceId],
        [IDL.Vec(BlinkRateMeasurement)],
        ['query'],
      ),
    'getBlinkRatesInTimeRange' : IDL.Func(
        [DeviceId, Timestamp, Timestamp],
        [IDL.Vec(BlinkRateMeasurement)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVibrationEvents' : IDL.Func(
        [DeviceId],
        [IDL.Vec(VibrationEvent)],
        ['query'],
      ),
    'getVibrationEventsInTimeRange' : IDL.Func(
        [DeviceId, Timestamp, Timestamp],
        [IDL.Vec(VibrationEvent)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordBlinkRate' : IDL.Func([DeviceId, BlinkRate], [], []),
    'recordVibrationEvent' : IDL.Func([DeviceId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };