/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BlinkRate = bigint;
export interface BlinkRateMeasurement {
  'userPrincipal' : [] | [Principal],
  'deviceId' : DeviceId,
  'timestamp' : Timestamp,
  'blinkRate' : BlinkRate,
}
export type DeviceId = string;
export interface SleepRecommendation {
  'suggestedBedtime' : Timestamp,
  'analysisWindowEnd' : Timestamp,
  'analysisWindowStart' : Timestamp,
  'suggestedWakeup' : Timestamp,
}
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VibrationEvent {
  'eventId' : VibrationEventId,
  'userPrincipal' : [] | [Principal],
  'deviceId' : DeviceId,
  'timestamp' : Timestamp,
}
export type VibrationEventId = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearOldData' : ActorMethod<[DeviceId, Timestamp], undefined>,
  'generateSleepRecommendation' : ActorMethod<
    [DeviceId, Timestamp, Timestamp],
    SleepRecommendation
  >,
  'getBlinkRates' : ActorMethod<[DeviceId], Array<BlinkRateMeasurement>>,
  'getBlinkRatesInTimeRange' : ActorMethod<
    [DeviceId, Timestamp, Timestamp],
    Array<BlinkRateMeasurement>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVibrationEvents' : ActorMethod<[DeviceId], Array<VibrationEvent>>,
  'getVibrationEventsInTimeRange' : ActorMethod<
    [DeviceId, Timestamp, Timestamp],
    Array<VibrationEvent>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordBlinkRate' : ActorMethod<[DeviceId, BlinkRate], undefined>,
  'recordVibrationEvent' : ActorMethod<[DeviceId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];