/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type DeviceId = string;
export interface BlinkRateMeasurement {
    userPrincipal?: Principal;
    deviceId: DeviceId;
    timestamp: Timestamp;
    blinkRate: BlinkRate;
}
export type Timestamp = bigint;
export type VibrationEventId = bigint;
export interface VibrationEvent {
    eventId: VibrationEventId;
    userPrincipal?: Principal;
    deviceId: DeviceId;
    timestamp: Timestamp;
}
export interface SleepRecommendation {
    suggestedBedtime: Timestamp;
    analysisWindowEnd: Timestamp;
    analysisWindowStart: Timestamp;
    suggestedWakeup: Timestamp;
}
export interface BlinkSummary {
    averageBlinkRate?: bigint;
    maxBlinkRate?: bigint;
    totalBlinks: bigint;
    userPrincipal?: Principal;
    deviceId: DeviceId;
    timestamp: Timestamp;
    minBlinkRate?: bigint;
}
export interface UserProfile {
    name: string;
}
export type BlinkRate = bigint;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDataPoint(deviceId: DeviceId, value: BlinkRate): Promise<number | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearOldData(deviceId: DeviceId, thresholdTime: Timestamp): Promise<void>;
    generateSleepRecommendation(deviceId: DeviceId, analysisWindowStart: Timestamp, analysisWindowEnd: Timestamp): Promise<SleepRecommendation>;
    getBlinkRates(deviceId: DeviceId): Promise<Array<BlinkRateMeasurement>>;
    getBlinkRatesInTimeRange(deviceId: DeviceId, startTime: Timestamp, endTime: Timestamp): Promise<Array<BlinkRateMeasurement>>;
    getBlinkSummariesInTimeRange(deviceId: DeviceId, startTime: Timestamp, endTime: Timestamp): Promise<Array<BlinkSummary>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMostRecentActuationLatency(): Promise<bigint | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVibrationEvents(deviceId: DeviceId): Promise<Array<VibrationEvent>>;
    getVibrationEventsInTimeRange(deviceId: DeviceId, startTime: Timestamp, endTime: Timestamp): Promise<Array<VibrationEvent>>;
    isCallerAdmin(): Promise<boolean>;
    recordBlinkRate(deviceId: DeviceId, blinkRate: BlinkRate): Promise<void>;
    recordBlinkSummary(deviceId: DeviceId, summary: BlinkSummary): Promise<void>;
    recordEyeClosedTimestamp(): Promise<void>;
    recordVibrationEvent(deviceId: DeviceId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    triggerVibrationAndCalculateLatency(): Promise<bigint>;
}
import type { BlinkRate as _BlinkRate, BlinkRateMeasurement as _BlinkRateMeasurement, BlinkSummary as _BlinkSummary, DeviceId as _DeviceId, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, VibrationEvent as _VibrationEvent, VibrationEventId as _VibrationEventId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDataPoint(arg0: DeviceId, arg1: BlinkRate): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addDataPoint(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDataPoint(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearOldData(arg0: DeviceId, arg1: Timestamp): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearOldData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearOldData(arg0, arg1);
            return result;
        }
    }
    async generateSleepRecommendation(arg0: DeviceId, arg1: Timestamp, arg2: Timestamp): Promise<SleepRecommendation> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSleepRecommendation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSleepRecommendation(arg0, arg1, arg2);
            return result;
        }
    }
    async getBlinkRates(arg0: DeviceId): Promise<Array<BlinkRateMeasurement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlinkRates(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlinkRates(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlinkRatesInTimeRange(arg0: DeviceId, arg1: Timestamp, arg2: Timestamp): Promise<Array<BlinkRateMeasurement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlinkRatesInTimeRange(arg0, arg1, arg2);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlinkRatesInTimeRange(arg0, arg1, arg2);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlinkSummariesInTimeRange(arg0: DeviceId, arg1: Timestamp, arg2: Timestamp): Promise<Array<BlinkSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlinkSummariesInTimeRange(arg0, arg1, arg2);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlinkSummariesInTimeRange(arg0, arg1, arg2);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMostRecentActuationLatency(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMostRecentActuationLatency();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMostRecentActuationLatency();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVibrationEvents(arg0: DeviceId): Promise<Array<VibrationEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVibrationEvents(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVibrationEvents(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVibrationEventsInTimeRange(arg0: DeviceId, arg1: Timestamp, arg2: Timestamp): Promise<Array<VibrationEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVibrationEventsInTimeRange(arg0, arg1, arg2);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVibrationEventsInTimeRange(arg0, arg1, arg2);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordBlinkRate(arg0: DeviceId, arg1: BlinkRate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordBlinkRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordBlinkRate(arg0, arg1);
            return result;
        }
    }
    async recordBlinkSummary(arg0: DeviceId, arg1: BlinkSummary): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordBlinkSummary(arg0, to_candid_BlinkSummary_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordBlinkSummary(arg0, to_candid_BlinkSummary_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async recordEyeClosedTimestamp(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordEyeClosedTimestamp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordEyeClosedTimestamp();
            return result;
        }
    }
    async recordVibrationEvent(arg0: DeviceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordVibrationEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordVibrationEvent(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async triggerVibrationAndCalculateLatency(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerVibrationAndCalculateLatency();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerVibrationAndCalculateLatency();
            return result;
        }
    }
}
function from_candid_BlinkRateMeasurement_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlinkRateMeasurement): BlinkRateMeasurement {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_BlinkSummary_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlinkSummary): BlinkSummary {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_VibrationEvent_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VibrationEvent): VibrationEvent {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averageBlinkRate: [] | [bigint];
    maxBlinkRate: [] | [bigint];
    totalBlinks: bigint;
    userPrincipal: [] | [Principal];
    deviceId: _DeviceId;
    timestamp: _Timestamp;
    minBlinkRate: [] | [bigint];
}): {
    averageBlinkRate?: bigint;
    maxBlinkRate?: bigint;
    totalBlinks: bigint;
    userPrincipal?: Principal;
    deviceId: DeviceId;
    timestamp: Timestamp;
    minBlinkRate?: bigint;
} {
    return {
        averageBlinkRate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.averageBlinkRate)),
        maxBlinkRate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.maxBlinkRate)),
        totalBlinks: value.totalBlinks,
        userPrincipal: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.userPrincipal)),
        deviceId: value.deviceId,
        timestamp: value.timestamp,
        minBlinkRate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.minBlinkRate))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eventId: _VibrationEventId;
    userPrincipal: [] | [Principal];
    deviceId: _DeviceId;
    timestamp: _Timestamp;
}): {
    eventId: VibrationEventId;
    userPrincipal?: Principal;
    deviceId: DeviceId;
    timestamp: Timestamp;
} {
    return {
        eventId: value.eventId,
        userPrincipal: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.userPrincipal)),
        deviceId: value.deviceId,
        timestamp: value.timestamp
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [Principal];
    deviceId: _DeviceId;
    timestamp: _Timestamp;
    blinkRate: _BlinkRate;
}): {
    userPrincipal?: Principal;
    deviceId: DeviceId;
    timestamp: Timestamp;
    blinkRate: BlinkRate;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.userPrincipal)),
        deviceId: value.deviceId,
        timestamp: value.timestamp,
        blinkRate: value.blinkRate
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VibrationEvent>): Array<VibrationEvent> {
    return value.map((x)=>from_candid_VibrationEvent_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlinkRateMeasurement>): Array<BlinkRateMeasurement> {
    return value.map((x)=>from_candid_BlinkRateMeasurement_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlinkSummary>): Array<BlinkSummary> {
    return value.map((x)=>from_candid_BlinkSummary_n9(_uploadFile, _downloadFile, x));
}
function to_candid_BlinkSummary_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlinkSummary): _BlinkSummary {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averageBlinkRate?: bigint;
    maxBlinkRate?: bigint;
    totalBlinks: bigint;
    userPrincipal?: Principal;
    deviceId: DeviceId;
    timestamp: Timestamp;
    minBlinkRate?: bigint;
}): {
    averageBlinkRate: [] | [bigint];
    maxBlinkRate: [] | [bigint];
    totalBlinks: bigint;
    userPrincipal: [] | [Principal];
    deviceId: _DeviceId;
    timestamp: _Timestamp;
    minBlinkRate: [] | [bigint];
} {
    return {
        averageBlinkRate: value.averageBlinkRate ? candid_some(value.averageBlinkRate) : candid_none(),
        maxBlinkRate: value.maxBlinkRate ? candid_some(value.maxBlinkRate) : candid_none(),
        totalBlinks: value.totalBlinks,
        userPrincipal: value.userPrincipal ? candid_some(value.userPrincipal) : candid_none(),
        deviceId: value.deviceId,
        timestamp: value.timestamp,
        minBlinkRate: value.minBlinkRate ? candid_some(value.minBlinkRate) : candid_none()
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
